version: "3.8"

services:
  postgres:
    image: postgres
    container_name: my_postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: adminpassword
      POSTGRES_DB: mydb
    ports:
      - "5432:5432"
    networks:
      - mynet

  streamlit:
    build: .
    container_name: streamlit_app
    ports:
      - "8504:8504"
    networks:
      - mynet
    depends_on:
      - postgres

networks:
  mynet:
