name: Docker Experiments Automation

on:
  push:
    branches:
      - main

jobs:
  run_experiments:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set Up Docker
      uses: docker/setup-buildx-action@v2

    - name: Run Automation Script
      run: |
        chmod +x run_experiments.sh
        ./run_experiments.sh
